#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: first-time Marquee-Pi setup (Pi, Windows tool, LaunchBox plugin).
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
REPO_URL="https://github.com/ScherzKeksFlo/Marquee-Pi"

banner "Marquee-Pi first-time setup"

stage "Write Raspberry Pi OS to the boot medium"
say "Use a microSD/USB medium of at least 16 GB. Writing erases it."
open_url "https://www.raspberrypi.com/software/"
step "Install and start Raspberry Pi Imager."
step "Device: Raspberry Pi 3. OS: Raspberry Pi OS (other) > Raspberry Pi OS Lite (32-bit)."
step "In the OS customisation, set hostname, user name + password, Wi-Fi incl. country, time zone, and enable SSH."
step "Write the medium, put it in the Pi and power it on."
pause "Pi has booted and joined Wi-Fi? Press Enter"

stage "Network addresses"
say "Windows reaches the Pi API on TCP 8765. Suggested direct Ethernet: Windows 10.0.0.1, Pi 10.0.0.10."
note "Only ONE matching IP configuration may be active on the direct link. Wi-Fi can stay on for SSH."
ask PI_HOST "Pi address Windows will use (e.g. 10.0.0.10):"
ask WINDOWS_IP "Windows address the Pi will see (e.g. 10.0.0.1):"
write_env PI_HOST "$PI_HOST"
write_env WINDOWS_IP "$WINDOWS_IP"
step "If you use the direct link, on the Pi (via SSH over Wi-Fi):"
say "  nmcli -g GENERAL.CONNECTION device show eth0"
say "  sudo nmcli connection modify '<profile>' ipv4.method manual ipv4.addresses $PI_HOST/24 ipv4.never-default yes"
say "  sudo nmcli connection up '<profile>'"
step "On Windows, give the Ethernet adapter the static address $WINDOWS_IP/24 (no gateway)."
pause "Can Windows ping $PI_HOST? Press Enter"

stage "Install the Marquee-Pi package on the Pi"
open_url "$REPO_URL/releases"
step "Download the latest marquee-pi_*_all.deb from the newest release."
step "Copy it to the Pi and install it (replace <user>@<wifi-host>):"
say "  scp marquee-pi_*_all.deb <user>@<wifi-host>:"
say "  ssh <user>@<wifi-host> 'sudo apt install ./marquee-pi_*_all.deb'"
note "The package installs the services and generates /etc/marquee-pi/config.json with a random token."
pause "apt finished without errors? Press Enter"

stage "Configure the Pi API"
step "On the Pi, edit the config: sudo nano /etc/marquee-pi/config.json"
say "  \"allowed_client_ips\": [\"$WINDOWS_IP\"]"
say "  \"bind\": \"$PI_HOST\"   (only for the direct link; keep 0.0.0.0 if Wi-Fi access is needed)"
say "  \"power_commands_enabled\": true   (lets the tray and touch menu restart/shut down the Pi)"
step "Apply it: sudo systemctl restart marquee-pi-api"
step "Show the token: sudo grep '\"token\"' /etc/marquee-pi/config.json"
ask_secret MARQUEE_PI_TOKEN "Paste the token:"
note "The token is kept in memory only, not written to disk by this wizard."

stage "Check that Windows can reach the Pi API"
if [[ -z "${MARQUEE_PI_TOKEN:-}" ]]; then
  warn "no token entered, skipping the check"
elif curl -fsS --max-time 8 -H "X-Marquee-Token: $MARQUEE_PI_TOKEN" "http://$PI_HOST:8765/v1/status"; then
  printf '\n  %s✓ Pi API answered%s\n' "$GREEN" "$RESET"
else
  printf '\n'
  warn "no valid answer from http://$PI_HOST:8765/v1/status"
  note "Check: token, allowed_client_ips = $WINDOWS_IP, bind, cable/IPs, 'systemctl is-active marquee-pi-api'."
  SKIPPED+=("Pi API check failed: fix connectivity before using the Windows tool")
fi
pause "Press Enter to continue"

stage "Windows tray tool"
open_url "$REPO_URL/releases"
step "Download and unpack Marquee-Pi-portable-win-x64.zip to a permanent folder."
step "Start Marquee-Pi.exe. Right-click the tray icon > Settings… > Connection."
say "  Pi address: http://$PI_HOST:8765"
say "  API token:  the token from the previous stage"
step "Save. The tray icon should show the connection as OK."
pause "Tray shows connected? Press Enter"

stage "LaunchBox / Big Box plugin"
step "Copy MarqueePiLaunchBox.dll from the unpacked ZIP to:"
say "  <LaunchBox>\Plugins\Marquee-Pi\\"
step "Fully close and restart LaunchBox / Big Box."
pause "LaunchBox restarted? Press Enter"

stage "Media, quiet boot and final test"
step "Tray > Manage media…: add files and assign roles: default media, boot splash (PNG/JPEG), optionally shutdown media."
step "Optional quiet boot, on the Pi (changes cmdline.txt; a backup is kept):"
say "  sudo marquee-pi-configure-quiet-boot && sudo reboot"
step "Start a game from Big Box. The marquee should appear; when the game ends the default media returns."
if confirm "Did the marquee show up and return to the default media?"; then
  printf '  %s✓ end-to-end test passed%s\n' "$GREEN" "$RESET"
else
  SKIPPED+=("End-to-end game test failed: see docs/architecture.md and the Windows shutdown.log")
fi

finish
